import type { Incident, RippleEdge, RippleNode } from "./types";

const nodes: RippleNode[] = [
  { id: "pad-left", name: "pad-left", kind: "library", ecosystem: "npm", version: "1.4.2", description: "Left-pad strings to a fixed width.", weeklyDownloads: 4_200_000, maintainers: 1, lastPublishDays: 1480, cves: [], layer: 0, alternative: "String.prototype.padStart" },
  { id: "tiny-hash", name: "tiny-hash", kind: "library", ecosystem: "npm", version: "2.1.0", description: "Fast non-cryptographic hash used across token and HTTP stacks.", weeklyDownloads: 8_900_000, maintainers: 1, lastPublishDays: 210, cves: [{ id: "CVE-2024-11011", severity: "high", title: "Timing leak in keyed hash" }], layer: 0, alternative: "node:crypto" },
  { id: "bit-flags", name: "bit-flags", kind: "library", ecosystem: "npm", version: "3.0.1", description: "Bitfield helpers.", weeklyDownloads: 2_100_000, maintainers: 2, lastPublishDays: 90, cves: [], layer: 0 },
  { id: "utf8-lite", name: "utf8-lite", kind: "library", ecosystem: "npm", version: "1.8.0", description: "UTF-8 encode/decode.", weeklyDownloads: 6_400_000, maintainers: 2, lastPublishDays: 40, cves: [], layer: 0 },
  { id: "path-norm", name: "path-norm", kind: "library", ecosystem: "npm", version: "0.9.4", description: "Normalize filesystem and URL paths.", weeklyDownloads: 3_300_000, maintainers: 1, lastPublishDays: 520, cves: [{ id: "CVE-2023-8821", severity: "medium", title: "Path traversal on Windows" }], layer: 0 },
  { id: "is-type", name: "is-type", kind: "library", ecosystem: "npm", version: "4.2.0", description: "Runtime type predicates.", weeklyDownloads: 11_000_000, maintainers: 3, lastPublishDays: 18, cves: [], layer: 0 },
  { id: "deep-eq", name: "deep-eq", kind: "library", ecosystem: "npm", version: "2.0.3", description: "Deep equality.", weeklyDownloads: 5_600_000, maintainers: 2, lastPublishDays: 70, cves: [], layer: 0 },
  { id: "once-fn", name: "once-fn", kind: "library", ecosystem: "npm", version: "1.1.1", description: "Run a function once.", weeklyDownloads: 9_200_000, maintainers: 1, lastPublishDays: 900, cves: [], layer: 0 },
  { id: "ms-parse", name: "ms-parse", kind: "library", ecosystem: "npm", version: "3.1.0", description: "Parse human time strings.", weeklyDownloads: 7_800_000, maintainers: 2, lastPublishDays: 25, cves: [], layer: 0 },
  { id: "safe-regex", name: "safe-regex", kind: "library", ecosystem: "npm", version: "2.4.0", description: "ReDoS-safe regex compile.", weeklyDownloads: 1_400_000, maintainers: 1, lastPublishDays: 310, cves: [], layer: 0 },
  { id: "mime-kind", name: "mime-kind", kind: "library", ecosystem: "npm", version: "1.6.2", description: "MIME sniffing.", weeklyDownloads: 2_800_000, maintainers: 2, lastPublishDays: 110, cves: [], layer: 0 },
  { id: "id-gen", name: "id-gen", kind: "library", ecosystem: "npm", version: "5.0.0", description: "UUID/ULID generation.", weeklyDownloads: 4_100_000, maintainers: 3, lastPublishDays: 12, cves: [], layer: 0 },

  { id: "stream-kit", name: "stream-kit", kind: "library", ecosystem: "npm", version: "4.8.1", description: "Composable object streams. Analog of a historically hijacked pipeline helper.", weeklyDownloads: 3_900_000, maintainers: 1, lastPublishDays: 640, cves: [{ id: "GHSA-stream-2018", severity: "critical", title: "Malicious maintainer injected credential harvester" }], layer: 1, alternative: "node:stream" },
  { id: "ua-parse", name: "ua-parse", kind: "library", ecosystem: "npm", version: "1.0.35", description: "User-agent parser.", weeklyDownloads: 5_200_000, maintainers: 1, lastPublishDays: 430, cves: [{ id: "GHSA-ua-2021", severity: "critical", title: "Hijacked account shipped crypto miner" }], layer: 1, alternative: "uap-core (maintained fork)" },
  { id: "color-fmt", name: "color-fmt", kind: "library", ecosystem: "npm", version: "1.4.0", description: "ANSI color formatting.", weeklyDownloads: 12_000_000, maintainers: 1, lastPublishDays: 800, cves: [{ id: "GHSA-color-2022", severity: "high", title: "Protestware infinite loop on specific locales" }], layer: 1, alternative: "picocolors" },
  { id: "yaml-tiny", name: "yaml-tiny", kind: "library", ecosystem: "npm", version: "2.3.1", description: "YAML 1.2 subset.", weeklyDownloads: 2_600_000, maintainers: 2, lastPublishDays: 55, cves: [], layer: 1 },
  { id: "arg-parse", name: "arg-parse", kind: "library", ecosystem: "npm", version: "1.2.8", description: "CLI argument parser.", weeklyDownloads: 4_700_000, maintainers: 2, lastPublishDays: 200, cves: [{ id: "CVE-2022-4411", severity: "medium", title: "Prototype pollution via flags" }], layer: 1 },
  { id: "qs-lite", name: "qs-lite", kind: "library", ecosystem: "npm", version: "6.11.0", description: "Query-string parse/serialize.", weeklyDownloads: 9_400_000, maintainers: 3, lastPublishDays: 33, cves: [], layer: 1 },
  { id: "semver-lite", name: "semver-lite", kind: "library", ecosystem: "npm", version: "7.5.4", description: "Semantic version compare.", weeklyDownloads: 10_100_000, maintainers: 4, lastPublishDays: 14, cves: [], layer: 1 },
  { id: "http-tiny", name: "http-tiny", kind: "library", ecosystem: "npm", version: "3.4.2", description: "Minimal HTTP client.", weeklyDownloads: 3_100_000, maintainers: 2, lastPublishDays: 47, cves: [], layer: 1 },
  { id: "crypto-mini", name: "crypto-mini", kind: "library", ecosystem: "npm", version: "0.8.9", description: "HMAC, digest, and constant-time compare.", weeklyDownloads: 2_200_000, maintainers: 2, lastPublishDays: 88, cves: [], layer: 1, alternative: "node:crypto" },
  { id: "json-stable", name: "json-stable", kind: "library", ecosystem: "npm", version: "1.0.2", description: "Deterministic JSON stringify.", weeklyDownloads: 1_900_000, maintainers: 1, lastPublishDays: 260, cves: [], layer: 1 },
  { id: "compress-xz", name: "compress-xz", kind: "library", ecosystem: "npm", version: "5.4.5", description: "Native-backed xz/lzma bindings. Analog of a widely trusted compressor.", weeklyDownloads: 1_100_000, maintainers: 2, lastPublishDays: 19, cves: [{ id: "CVE-2024-3094", severity: "critical", title: "Supply-chain backdoor in build scripts" }], layer: 1, alternative: "node:zlib / zstd" },
  { id: "protobuf-lite", name: "protobuf-lite", kind: "library", ecosystem: "npm", version: "7.2.0", description: "Compact protobuf codec.", weeklyDownloads: 1_600_000, maintainers: 3, lastPublishDays: 61, cves: [], layer: 1 },
  { id: "log-fmt", name: "log-fmt", kind: "library", ecosystem: "npm", version: "4.1.0", description: "Structured logger.", weeklyDownloads: 2_400_000, maintainers: 2, lastPublishDays: 22, cves: [], layer: 1 },
  { id: "event-bus", name: "event-bus", kind: "library", ecosystem: "npm", version: "2.0.0", description: "In-process pub/sub.", weeklyDownloads: 1_800_000, maintainers: 2, lastPublishDays: 101, cves: [], layer: 1 },
  { id: "metric-core", name: "metric-core", kind: "library", ecosystem: "npm", version: "0.12.3", description: "Counters, histograms, exporters.", weeklyDownloads: 980_000, maintainers: 3, lastPublishDays: 8, cves: [], layer: 1 },
  { id: "schema-guard", name: "schema-guard", kind: "library", ecosystem: "npm", version: "3.9.1", description: "Runtime schema validation.", weeklyDownloads: 2_050_000, maintainers: 3, lastPublishDays: 16, cves: [], layer: 1 },
  { id: "fetch-retry", name: "fetch-retry", kind: "library", ecosystem: "npm", version: "1.7.0", description: "Retry/backoff wrapper for HTTP.", weeklyDownloads: 1_250_000, maintainers: 1, lastPublishDays: 140, cves: [], layer: 1 },
  { id: "config-load", name: "config-load", kind: "library", ecosystem: "npm", version: "2.2.4", description: "Layered config from files and env.", weeklyDownloads: 1_480_000, maintainers: 2, lastPublishDays: 44, cves: [], layer: 1 },
  { id: "token-core", name: "token-core", kind: "library", ecosystem: "npm", version: "9.1.2", description: "JWT/Paseto issue and verify.", weeklyDownloads: 1_720_000, maintainers: 2, lastPublishDays: 27, cves: [{ id: "CVE-2023-4011", severity: "high", title: "alg=none accepted when key omitted" }], layer: 1 },

  { id: "aether-web", name: "aether-web", kind: "framework", ecosystem: "npm", version: "14.2.1", description: "SSR/web framework.", weeklyDownloads: 420_000, maintainers: 8, lastPublishDays: 6, cves: [], layer: 2 },
  { id: "aether-api", name: "aether-api", kind: "framework", ecosystem: "npm", version: "8.4.0", description: "HTTP API toolkit.", weeklyDownloads: 310_000, maintainers: 6, lastPublishDays: 9, cves: [], layer: 2 },
  { id: "aether-auth", name: "aether-auth", kind: "framework", ecosystem: "npm", version: "5.0.3", description: "Session and token auth.", weeklyDownloads: 260_000, maintainers: 4, lastPublishDays: 11, cves: [], layer: 2 },
  { id: "aether-data", name: "aether-data", kind: "framework", ecosystem: "npm", version: "3.6.1", description: "Serialization, migrations, storage adapters.", weeklyDownloads: 190_000, maintainers: 4, lastPublishDays: 20, cves: [], layer: 2 },
  { id: "aether-ui", name: "aether-ui", kind: "framework", ecosystem: "npm", version: "6.1.0", description: "Component runtime and theming.", weeklyDownloads: 280_000, maintainers: 5, lastPublishDays: 5, cves: [], layer: 2 },
  { id: "aether-jobs", name: "aether-jobs", kind: "framework", ecosystem: "npm", version: "2.8.2", description: "Queues and workers.", weeklyDownloads: 140_000, maintainers: 3, lastPublishDays: 17, cves: [], layer: 2 },
  { id: "aether-ml", name: "aether-ml", kind: "framework", ecosystem: "npm", version: "0.4.9", description: "Feature pipes and model serving.", weeklyDownloads: 72_000, maintainers: 3, lastPublishDays: 13, cves: [], layer: 2 },

  { id: "bank", name: "Aether Bank", kind: "app", ecosystem: "npm", version: "2026.9", description: "Retail banking web and API.", weeklyDownloads: 0, maintainers: 40, lastPublishDays: 1, cves: [], layer: 3, org: "Aether Financial", domain: "finance" },
  { id: "health", name: "Harbor Health", kind: "app", ecosystem: "npm", version: "2026.8", description: "Clinical records portal.", weeklyDownloads: 0, maintainers: 28, lastPublishDays: 2, cves: [], layer: 3, org: "Harbor", domain: "health" },
  { id: "civic", name: "Civic Portal", kind: "app", ecosystem: "npm", version: "2026.4", description: "Benefits and identity for a city.", weeklyDownloads: 0, maintainers: 12, lastPublishDays: 4, cves: [], layer: 3, org: "Metro City", domain: "gov" },
  { id: "retail", name: "Northwind Retail", kind: "app", ecosystem: "npm", version: "2026.9", description: "Storefront and checkout.", weeklyDownloads: 0, maintainers: 18, lastPublishDays: 1, cves: [], layer: 3, org: "Northwind", domain: "commerce" },
  { id: "pulse", name: "Pulse Analytics", kind: "app", ecosystem: "npm", version: "2026.9", description: "Product analytics warehouse.", weeklyDownloads: 0, maintainers: 15, lastPublishDays: 1, cves: [], layer: 3, org: "Pulse", domain: "data" },
  { id: "chat", name: "Flux Chat", kind: "app", ecosystem: "npm", version: "2026.7", description: "Customer messaging.", weeklyDownloads: 0, maintainers: 10, lastPublishDays: 3, cves: [], layer: 3, org: "Flux", domain: "saas" },
  { id: "ledger", name: "Ledger Ops", kind: "app", ecosystem: "npm", version: "2026.9", description: "Internal ledger and reconciliation.", weeklyDownloads: 0, maintainers: 22, lastPublishDays: 1, cves: [], layer: 3, org: "Aether Financial", domain: "finance" },
  { id: "maps", name: "Atlas Maps", kind: "app", ecosystem: "npm", version: "2026.5", description: "Geospatial tiles and routing.", weeklyDownloads: 0, maintainers: 9, lastPublishDays: 6, cves: [], layer: 3, org: "Atlas", domain: "infra" },
  { id: "cms", name: "Beacon CMS", kind: "app", ecosystem: "npm", version: "2026.6", description: "Content and publishing.", weeklyDownloads: 0, maintainers: 7, lastPublishDays: 2, cves: [], layer: 3, org: "Beacon", domain: "saas" },
  { id: "logistics", name: "Drift Logistics", kind: "app", ecosystem: "npm", version: "2026.8", description: "Routing, ETAs, warehouse jobs.", weeklyDownloads: 0, maintainers: 14, lastPublishDays: 2, cves: [], layer: 3, org: "Drift", domain: "ops" },
  { id: "docs", name: "Quill Docs", kind: "app", ecosystem: "npm", version: "2026.3", description: "Collaborative documents.", weeklyDownloads: 0, maintainers: 8, lastPublishDays: 8, cves: [], layer: 3, org: "Quill", domain: "saas" },
  { id: "ci", name: "Helix CI", kind: "app", ecosystem: "npm", version: "2026.9", description: "Build and artifact pipeline.", weeklyDownloads: 0, maintainers: 11, lastPublishDays: 1, cves: [], layer: 3, org: "Helix", domain: "infra" },
];

const E = (from: string, to: string, kind: RippleEdge["kind"] = "runtime"): RippleEdge => ({
  from,
  to,
  kind,
});

const edges: RippleEdge[] = [
  E("stream-kit", "once-fn"),
  E("stream-kit", "is-type"),
  E("ua-parse", "utf8-lite"),
  E("ua-parse", "is-type"),
  E("ua-parse", "safe-regex"),
  E("color-fmt", "bit-flags"),
  E("color-fmt", "pad-left"),
  E("yaml-tiny", "utf8-lite"),
  E("yaml-tiny", "deep-eq"),
  E("arg-parse", "is-type"),
  E("arg-parse", "pad-left"),
  E("qs-lite", "utf8-lite"),
  E("qs-lite", "path-norm"),
  E("semver-lite", "pad-left"),
  E("semver-lite", "is-type"),
  E("http-tiny", "tiny-hash"),
  E("http-tiny", "qs-lite"),
  E("http-tiny", "once-fn"),
  E("crypto-mini", "tiny-hash"),
  E("crypto-mini", "bit-flags"),
  E("json-stable", "deep-eq"),
  E("json-stable", "utf8-lite"),
  E("compress-xz", "bit-flags"),
  E("compress-xz", "utf8-lite"),
  E("protobuf-lite", "bit-flags"),
  E("protobuf-lite", "utf8-lite"),
  E("protobuf-lite", "is-type"),
  E("log-fmt", "color-fmt"),
  E("log-fmt", "pad-left"),
  E("log-fmt", "ms-parse"),
  E("event-bus", "stream-kit"),
  E("event-bus", "once-fn"),
  E("metric-core", "ms-parse"),
  E("metric-core", "once-fn"),
  E("schema-guard", "is-type"),
  E("schema-guard", "deep-eq"),
  E("schema-guard", "json-stable"),
  E("fetch-retry", "http-tiny"),
  E("fetch-retry", "ms-parse"),
  E("fetch-retry", "once-fn"),
  E("config-load", "yaml-tiny"),
  E("config-load", "arg-parse"),
  E("config-load", "json-stable"),
  E("token-core", "crypto-mini"),
  E("token-core", "tiny-hash"),
  E("token-core", "ms-parse"),
  E("mime-kind", "is-type"),

  E("aether-web", "event-bus"),
  E("aether-web", "fetch-retry"),
  E("aether-web", "token-core"),
  E("aether-web", "log-fmt"),
  E("aether-web", "config-load"),
  E("aether-web", "ua-parse"),
  E("aether-web", "semver-lite", "dev"),
  E("aether-api", "http-tiny"),
  E("aether-api", "token-core"),
  E("aether-api", "schema-guard"),
  E("aether-api", "log-fmt"),
  E("aether-api", "config-load"),
  E("aether-api", "protobuf-lite"),
  E("aether-auth", "token-core"),
  E("aether-auth", "crypto-mini"),
  E("aether-auth", "fetch-retry"),
  E("aether-data", "schema-guard"),
  E("aether-data", "yaml-tiny"),
  E("aether-data", "json-stable"),
  E("aether-data", "compress-xz"),
  E("aether-ui", "color-fmt"),
  E("aether-ui", "ua-parse"),
  E("aether-ui", "event-bus"),
  E("aether-ui", "log-fmt"),
  E("aether-jobs", "stream-kit"),
  E("aether-jobs", "event-bus"),
  E("aether-jobs", "metric-core"),
  E("aether-jobs", "config-load"),
  E("aether-ml", "protobuf-lite"),
  E("aether-ml", "metric-core"),
  E("aether-ml", "compress-xz"),
  E("aether-ml", "json-stable"),

  E("bank", "aether-web"),
  E("bank", "aether-api"),
  E("bank", "aether-auth"),
  E("bank", "aether-data"),
  E("health", "aether-web"),
  E("health", "aether-api"),
  E("health", "aether-auth"),
  E("health", "aether-data"),
  E("civic", "aether-web"),
  E("civic", "aether-auth"),
  E("civic", "aether-ui"),
  E("retail", "aether-web"),
  E("retail", "aether-ui"),
  E("retail", "aether-jobs"),
  E("pulse", "aether-api"),
  E("pulse", "aether-ml"),
  E("pulse", "aether-data"),
  E("chat", "aether-web"),
  E("chat", "aether-ui"),
  E("chat", "aether-auth"),
  E("ledger", "aether-api"),
  E("ledger", "aether-auth"),
  E("ledger", "aether-jobs"),
  E("ledger", "aether-data"),
  E("maps", "aether-web"),
  E("maps", "aether-ui"),
  E("maps", "aether-data"),
  E("cms", "aether-web"),
  E("cms", "aether-ui"),
  E("cms", "aether-jobs"),
  E("logistics", "aether-api"),
  E("logistics", "aether-jobs"),
  E("logistics", "aether-ml"),
  E("docs", "aether-web"),
  E("docs", "aether-ui"),
  E("docs", "aether-data"),
  E("ci", "aether-api"),
  E("ci", "aether-jobs"),
  E("ci", "aether-auth"),
  E("ci", "compress-xz"),
];

export const INCIDENTS: Incident[] = [
  {
    id: "stream-2018",
    year: 2018,
    title: "stream-kit takeover",
    analog: "event-stream",
    packageId: "stream-kit",
    attack: "malicious-release",
    summary:
      "A new maintainer published a minor version that harvested wallets from downstream build machines. Direct dependents looked harmless; the blast radius was the job and web frameworks sitting two hops up.",
    lesson: "Maintainer transfer on a high-betweenness package is a first-class risk signal, independent of CVSS.",
  },
  {
    id: "ua-2021",
    year: 2021,
    title: "ua-parse account hijack",
    analog: "ua-parser-js",
    packageId: "ua-parse",
    attack: "account-takeover",
    summary:
      "The publisher account was compromised. Three poisoned versions reached every web and UI framework that fingerprints browsers.",
    lesson: "Account-takeover risk scales with how many applications import a parser they barely think about.",
  },
  {
    id: "color-2022",
    year: 2022,
    title: "color-fmt protestware",
    analog: "colors.js / faker",
    packageId: "color-fmt",
    attack: "protestware",
    summary:
      "A logger dependency pulled in color-fmt. Production processes in specific regions entered infinite loops — availability impact with no CVE at publish time.",
    lesson: "Integrity is not just memory safety. Political or personal protestware rides the same edges as a backdoor.",
  },
  {
    id: "xz-2024",
    year: 2024,
    title: "compress-xz build backdoor",
    analog: "xz utils",
    packageId: "compress-xz",
    attack: "build-backdoor",
    summary:
      "A patient contributor landed a test-file payload that only activated in release tarballs. Data and ML frameworks, plus Helix CI's artifact path, inherited a remote backdoor.",
    lesson: "Native build scripts and 'test' assets are in the trust boundary. Downstream criticality dwarfs the package's own score.",
  },
  {
    id: "pad-2016",
    year: 2016,
    title: "pad-left unpublished",
    analog: "left-pad",
    packageId: "pad-left",
    attack: "malicious-release",
    summary:
      "An 11-line package disappeared from the registry and broke color, CLI, and semver stacks in the same afternoon.",
    lesson: "Trivial packages with huge in-degree are structural single points of failure even with zero CVEs.",
  },
];

export const NODES = nodes;
export const EDGES = edges;

export const NODE_MAP: Record<string, RippleNode> = Object.fromEntries(nodes.map((n) => [n.id, n]));
